// Bundles the ONE macro engine (calculator2-demo/src/lib/calculations.ts, the
// same source the CW calculator uses and tests/macro_parity checks against the
// worker) into pescodial/static/js/pd-macros.js as window.PDMacros.
// PescoDial must never carry its own formula. Re-run after any engine change;
// tests/pd-macros-bundle.test.mjs fails if the bundle drifts from the worker.
//
// Run: node pescodial/scripts/build_pd_calc.mjs   (needs calculator2-demo deps: npm ci there)
import { build } from '../../calculator2-demo/node_modules/esbuild/lib/main.js';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const entry = path.join(root, 'pescodial/scripts/.pd-calc-entry.ts');
import { writeFileSync, unlinkSync } from 'node:fs';
writeFileSync(entry, "export { calculateMacrosCanonical } from '../../calculator2-demo/src/lib/calculations';\n");
try {
  await build({
    entryPoints: [entry], bundle: true, format: 'iife', globalName: 'PDMacros',
    platform: 'browser', target: 'es2017', minify: false, legalComments: 'none',
    outfile: path.join(root, 'pescodial/static/js/pd-macros.js'),
    banner: { js: '/* GENERATED by pescodial/scripts/build_pd_calc.mjs from calculator2-demo/src/lib/calculations.ts. Do not edit. */' },
    drop: ['console'],
  });
  console.log('built pescodial/static/js/pd-macros.js');
} finally { unlinkSync(entry); }
