// GENERATED by pescodial/scripts/build_pd_foods.py from USDA FoodData Central,
// SR Legacy (April 2018 release). Values per 100 g. Do not hand-edit.
// Animal foods with no USDA fiber row carry fiber 0.
export const PD_FOODS = {
 "salmon": {
  "fdcId": 175167,
  "usda": "Fish, salmon, Atlantic, farmed, raw",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Seafood",
  "per100g": {
   "kcal": 208.0,
   "protein": 20.42,
   "fat": 13.42,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "cod": {
  "fdcId": 171955,
  "usda": "Fish, cod, Atlantic, raw",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Seafood",
  "per100g": {
   "kcal": 82.0,
   "protein": 17.81,
   "fat": 0.67,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "shrimp": {
  "fdcId": 175179,
  "usda": "Crustaceans, shrimp, raw",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Seafood",
  "per100g": {
   "kcal": 85.0,
   "protein": 20.1,
   "fat": 0.51,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "sardines": {
  "fdcId": 175139,
  "usda": "Fish, sardine, Atlantic, canned in oil, drained solids with bone",
  "unit": "can",
  "gramsPerUnit": 92,
  "section": "Seafood",
  "per100g": {
   "kcal": 208.0,
   "protein": 24.62,
   "fat": 11.45,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "tuna": {
  "fdcId": 173709,
  "usda": "Fish, tuna, light, canned in water, drained solids (Includes foods for USDA's Food Distribution Program)",
  "unit": "can",
  "gramsPerUnit": 142,
  "section": "Seafood",
  "per100g": {
   "kcal": 86.0,
   "protein": 19.44,
   "fat": 0.96,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "trout": {
  "fdcId": 173717,
  "usda": "Fish, trout, rainbow, farmed, raw",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Seafood",
  "per100g": {
   "kcal": 141.0,
   "protein": 19.94,
   "fat": 6.18,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "tilapia": {
  "fdcId": 175176,
  "usda": "Fish, tilapia, raw",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Seafood",
  "per100g": {
   "kcal": 96.0,
   "protein": 20.08,
   "fat": 1.7,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "eggs": {
  "fdcId": 171287,
  "usda": "Egg, whole, raw, fresh",
  "unit": "each",
  "gramsPerUnit": 50,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 143.0,
   "protein": 12.56,
   "fat": 9.51,
   "carbs": 0.72,
   "fiber": 0.0
  }
 },
 "greek_yogurt": {
  "fdcId": 170903,
  "usda": "Yogurt, Greek, plain, lowfat",
  "unit": "cup",
  "gramsPerUnit": 245,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 73.0,
   "protein": 9.95,
   "fat": 1.92,
   "carbs": 3.94,
   "fiber": 0.0
  }
 },
 "milk": {
  "fdcId": 171267,
  "usda": "Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D",
  "unit": "cup",
  "gramsPerUnit": 244,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 50.0,
   "protein": 3.3,
   "fat": 1.98,
   "carbs": 4.8,
   "fiber": 0.0
  }
 },
 "feta": {
  "fdcId": 173420,
  "usda": "Cheese, feta",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 265.0,
   "protein": 14.21,
   "fat": 21.49,
   "carbs": 3.88,
   "fiber": 0.0
  }
 },
 "parmesan": {
  "fdcId": 171247,
  "usda": "Cheese, parmesan, grated",
  "unit": "tbsp",
  "gramsPerUnit": 5,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 420.0,
   "protein": 28.42,
   "fat": 27.84,
   "carbs": 13.91,
   "fiber": 0.0
  }
 },
 "string_cheese": {
  "fdcId": 170847,
  "usda": "Cheese, mozzarella, part skim milk",
  "unit": "stick",
  "gramsPerUnit": 28,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 254.0,
   "protein": 24.26,
   "fat": 15.92,
   "carbs": 2.77,
   "fiber": 0.0
  }
 },
 "blueberries": {
  "fdcId": 171711,
  "usda": "Blueberries, raw",
  "unit": "cup",
  "gramsPerUnit": 148,
  "section": "Produce",
  "per100g": {
   "kcal": 57.0,
   "protein": 0.74,
   "fat": 0.33,
   "carbs": 14.49,
   "fiber": 2.4
  }
 },
 "apple": {
  "fdcId": 171688,
  "usda": "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)",
  "unit": "each",
  "gramsPerUnit": 182,
  "section": "Produce",
  "per100g": {
   "kcal": 52.0,
   "protein": 0.26,
   "fat": 0.17,
   "carbs": 13.81,
   "fiber": 2.4
  }
 },
 "orange": {
  "fdcId": 169097,
  "usda": "Oranges, raw, all commercial varieties",
  "unit": "each",
  "gramsPerUnit": 131,
  "section": "Produce",
  "per100g": {
   "kcal": 47.0,
   "protein": 0.94,
   "fat": 0.12,
   "carbs": 11.75,
   "fiber": 2.4
  }
 },
 "pear": {
  "fdcId": 169118,
  "usda": "Pears, raw",
  "unit": "each",
  "gramsPerUnit": 178,
  "section": "Produce",
  "per100g": {
   "kcal": 57.0,
   "protein": 0.36,
   "fat": 0.14,
   "carbs": 15.23,
   "fiber": 3.1
  }
 },
 "dates": {
  "fdcId": 168191,
  "usda": "Dates, medjool",
  "unit": "each",
  "gramsPerUnit": 24,
  "section": "Pantry",
  "per100g": {
   "kcal": 277.0,
   "protein": 1.81,
   "fat": 0.15,
   "carbs": 74.97,
   "fiber": 6.7
  }
 },
 "walnuts": {
  "fdcId": 170187,
  "usda": "Nuts, walnuts, english",
  "unit": "tbsp",
  "gramsPerUnit": 7.5,
  "section": "Pantry",
  "per100g": {
   "kcal": 654.0,
   "protein": 15.23,
   "fat": 65.21,
   "carbs": 13.71,
   "fiber": 6.7
  }
 },
 "almonds": {
  "fdcId": 170567,
  "usda": "Nuts, almonds",
  "unit": "tbsp",
  "gramsPerUnit": 9,
  "section": "Pantry",
  "per100g": {
   "kcal": 579.0,
   "protein": 21.15,
   "fat": 49.93,
   "carbs": 21.55,
   "fiber": 12.5
  }
 },
 "almond_butter": {
  "fdcId": 168588,
  "usda": "Nuts, almond butter, plain, without salt added",
  "unit": "tbsp",
  "gramsPerUnit": 16,
  "section": "Pantry",
  "per100g": {
   "kcal": 614.0,
   "protein": 20.96,
   "fat": 55.5,
   "carbs": 18.82,
   "fiber": 10.3
  }
 },
 "chia": {
  "fdcId": 170554,
  "usda": "Seeds, chia seeds, dried",
  "unit": "tbsp",
  "gramsPerUnit": 12,
  "section": "Pantry",
  "per100g": {
   "kcal": 486.0,
   "protein": 16.54,
   "fat": 30.74,
   "carbs": 42.12,
   "fiber": 34.4
  }
 },
 "oats": {
  "fdcId": 173904,
  "usda": "Cereals, oats, regular and quick, not fortified, dry",
  "unit": "cup",
  "gramsPerUnit": 81,
  "section": "Pantry",
  "per100g": {
   "kcal": 379.0,
   "protein": 13.15,
   "fat": 6.52,
   "carbs": 67.7,
   "fiber": 10.1
  }
 },
 "wholegrain_bread": {
  "fdcId": 172688,
  "usda": "Bread, whole-wheat, commercially prepared",
  "unit": "slice",
  "gramsPerUnit": 32,
  "section": "Bakery",
  "per100g": {
   "kcal": 252.0,
   "protein": 12.45,
   "fat": 3.5,
   "carbs": 42.71,
   "fiber": 6.0
  }
 },
 "pita": {
  "fdcId": 174916,
  "usda": "Bread, pita, whole-wheat",
  "unit": "each",
  "gramsPerUnit": 64,
  "section": "Bakery",
  "per100g": {
   "kcal": 262.0,
   "protein": 9.8,
   "fat": 1.71,
   "carbs": 55.89,
   "fiber": 6.1
  }
 },
 "quinoa": {
  "fdcId": 168917,
  "usda": "Quinoa, cooked",
  "unit": "cup",
  "gramsPerUnit": 185,
  "section": "Pantry",
  "per100g": {
   "kcal": 120.0,
   "protein": 4.4,
   "fat": 1.92,
   "carbs": 21.3,
   "fiber": 2.8
  }
 },
 "bulgur": {
  "fdcId": 170287,
  "usda": "Bulgur, cooked",
  "unit": "cup",
  "gramsPerUnit": 182,
  "section": "Pantry",
  "per100g": {
   "kcal": 83.0,
   "protein": 3.08,
   "fat": 0.24,
   "carbs": 18.58,
   "fiber": 4.5
  }
 },
 "ww_pasta": {
  "fdcId": 168910,
  "usda": "Pasta, whole-wheat, cooked (Includes foods for USDA's Food Distribution Program)",
  "unit": "cup",
  "gramsPerUnit": 140,
  "section": "Pantry",
  "per100g": {
   "kcal": 149.0,
   "protein": 5.99,
   "fat": 1.71,
   "carbs": 30.07,
   "fiber": 3.9
  }
 },
 "potatoes": {
  "fdcId": 170438,
  "usda": "Potatoes, boiled, cooked in skin, flesh, without salt",
  "unit": "cup",
  "gramsPerUnit": 156,
  "section": "Produce",
  "per100g": {
   "kcal": 87.0,
   "protein": 1.87,
   "fat": 0.1,
   "carbs": 20.13,
   "fiber": 1.8
  }
 },
 "lentils": {
  "fdcId": 172421,
  "usda": "Lentils, mature seeds, cooked, boiled, without salt",
  "unit": "cup",
  "gramsPerUnit": 198,
  "section": "Pantry",
  "per100g": {
   "kcal": 116.0,
   "protein": 9.02,
   "fat": 0.38,
   "carbs": 20.13,
   "fiber": 7.9
  }
 },
 "chickpeas": {
  "fdcId": 173801,
  "usda": "Chickpeas (garbanzo beans, bengal gram), mature seeds, canned, drained, rinsed in tap water",
  "unit": "cup",
  "gramsPerUnit": 152,
  "section": "Pantry",
  "per100g": {
   "kcal": 138.0,
   "protein": 7.04,
   "fat": 2.47,
   "carbs": 22.87,
   "fiber": 6.3
  }
 },
 "white_beans": {
  "fdcId": 175204,
  "usda": "Beans, white, mature seeds, canned",
  "unit": "cup",
  "gramsPerUnit": 262,
  "section": "Pantry",
  "per100g": {
   "kcal": 114.0,
   "protein": 7.26,
   "fat": 0.29,
   "carbs": 21.2,
   "fiber": 4.8
  }
 },
 "hummus": {
  "fdcId": 174289,
  "usda": "Hummus, commercial",
  "unit": "tbsp",
  "gramsPerUnit": 15,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 237.0,
   "protein": 7.78,
   "fat": 17.82,
   "carbs": 15.0,
   "fiber": 5.5
  }
 },
 "spinach": {
  "fdcId": 168462,
  "usda": "Spinach, raw",
  "unit": "cup",
  "gramsPerUnit": 30,
  "section": "Produce",
  "per100g": {
   "kcal": 23.0,
   "protein": 2.86,
   "fat": 0.39,
   "carbs": 3.63,
   "fiber": 2.2
  }
 },
 "greens": {
  "fdcId": 169247,
  "usda": "Lettuce, cos or romaine, raw",
  "unit": "cup",
  "gramsPerUnit": 47,
  "section": "Produce",
  "per100g": {
   "kcal": 17.0,
   "protein": 1.23,
   "fat": 0.3,
   "carbs": 3.29,
   "fiber": 2.1
  }
 },
 "green_beans": {
  "fdcId": 169141,
  "usda": "Beans, snap, green, cooked, boiled, drained, without salt",
  "unit": "cup",
  "gramsPerUnit": 125,
  "section": "Produce",
  "per100g": {
   "kcal": 35.0,
   "protein": 1.89,
   "fat": 0.28,
   "carbs": 7.88,
   "fiber": 3.2
  }
 },
 "tomatoes": {
  "fdcId": 170457,
  "usda": "Tomatoes, red, ripe, raw, year round average",
  "unit": "cup",
  "gramsPerUnit": 149,
  "section": "Produce",
  "per100g": {
   "kcal": 18.0,
   "protein": 0.88,
   "fat": 0.2,
   "carbs": 3.89,
   "fiber": 1.2
  }
 },
 "bell_pepper": {
  "fdcId": 170108,
  "usda": "Peppers, sweet, red, raw",
  "unit": "cup",
  "gramsPerUnit": 149,
  "section": "Produce",
  "per100g": {
   "kcal": 26.0,
   "protein": 0.99,
   "fat": 0.3,
   "carbs": 6.03,
   "fiber": 2.1
  }
 },
 "cucumber": {
  "fdcId": 168409,
  "usda": "Cucumber, with peel, raw",
  "unit": "cup",
  "gramsPerUnit": 104,
  "section": "Produce",
  "per100g": {
   "kcal": 15.0,
   "protein": 0.65,
   "fat": 0.11,
   "carbs": 3.63,
   "fiber": 0.5
  }
 },
 "carrots": {
  "fdcId": 170393,
  "usda": "Carrots, raw",
  "unit": "cup",
  "gramsPerUnit": 128,
  "section": "Produce",
  "per100g": {
   "kcal": 41.0,
   "protein": 0.93,
   "fat": 0.24,
   "carbs": 9.58,
   "fiber": 2.8
  }
 },
 "broccoli": {
  "fdcId": 169967,
  "usda": "Broccoli, cooked, boiled, drained, without salt",
  "unit": "cup",
  "gramsPerUnit": 156,
  "section": "Produce",
  "per100g": {
   "kcal": 35.0,
   "protein": 2.38,
   "fat": 0.41,
   "carbs": 7.18,
   "fiber": 3.3
  }
 },
 "zucchini": {
  "fdcId": 169292,
  "usda": "Squash, summer, zucchini, includes skin, cooked, boiled, drained, without salt",
  "unit": "cup",
  "gramsPerUnit": 180,
  "section": "Produce",
  "per100g": {
   "kcal": 15.0,
   "protein": 1.14,
   "fat": 0.36,
   "carbs": 2.69,
   "fiber": 1.0
  }
 },
 "olive_oil": {
  "fdcId": 171413,
  "usda": "Oil, olive, salad or cooking",
  "unit": "tbsp",
  "gramsPerUnit": 13.5,
  "section": "Pantry",
  "per100g": {
   "kcal": 884.0,
   "protein": 0.0,
   "fat": 100.0,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "olives": {
  "fdcId": 169094,
  "usda": "Olives, ripe, canned (small-extra large)",
  "unit": "each",
  "gramsPerUnit": 4.4,
  "section": "Pantry",
  "per100g": {
   "kcal": 116.0,
   "protein": 0.84,
   "fat": 10.9,
   "carbs": 6.04,
   "fiber": 1.6
  }
 },
 "avocado": {
  "fdcId": 171705,
  "usda": "Avocados, raw, all commercial varieties",
  "unit": "each",
  "gramsPerUnit": 150,
  "section": "Produce",
  "per100g": {
   "kcal": 160.0,
   "protein": 2.0,
   "fat": 14.66,
   "carbs": 8.53,
   "fiber": 6.7
  }
 },
 "tomato_sauce": {
  "fdcId": 170054,
  "usda": "Tomato products, canned, sauce",
  "unit": "cup",
  "gramsPerUnit": 245,
  "section": "Pantry",
  "per100g": {
   "kcal": 24.0,
   "protein": 1.2,
   "fat": 0.3,
   "carbs": 5.31,
   "fiber": 1.5
  }
 },
 "lemon": {
  "fdcId": 167746,
  "usda": "Lemons, raw, without peel",
  "unit": "each",
  "gramsPerUnit": 58,
  "section": "Produce",
  "per100g": {
   "kcal": 29.0,
   "protein": 1.1,
   "fat": 0.3,
   "carbs": 9.32,
   "fiber": 2.8
  }
 },
 "butter": {
  "fdcId": 173410,
  "usda": "Butter, salted",
  "unit": "tbsp",
  "gramsPerUnit": 14.2,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 717.0,
   "protein": 0.85,
   "fat": 81.11,
   "carbs": 0.06,
   "fiber": 0.0
  }
 },
 "cheddar": {
  "fdcId": 173414,
  "usda": "Cheese, cheddar (Includes foods for USDA's Food Distribution Program)",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 403.0,
   "protein": 22.87,
   "fat": 33.31,
   "carbs": 3.37,
   "fiber": 0.0
  }
 },
 "cream_cheese": {
  "fdcId": 173418,
  "usda": "Cheese, cream",
  "unit": "tbsp",
  "gramsPerUnit": 14.5,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 350.0,
   "protein": 6.15,
   "fat": 34.44,
   "carbs": 5.52,
   "fiber": 0.0
  }
 },
 "heavy_cream": {
  "fdcId": 170859,
  "usda": "Cream, fluid, heavy whipping",
  "unit": "tbsp",
  "gramsPerUnit": 15,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 340.0,
   "protein": 2.84,
   "fat": 36.08,
   "carbs": 2.84,
   "fiber": 0.0
  }
 },
 "whole_greek_yogurt": {
  "fdcId": 171304,
  "usda": "Yogurt, Greek, plain, whole milk",
  "unit": "cup",
  "gramsPerUnit": 245,
  "section": "Dairy and eggs",
  "per100g": {
   "kcal": 97.0,
   "protein": 9.0,
   "fat": 5.0,
   "carbs": 3.98,
   "fiber": 0.0
  }
 },
 "mackerel": {
  "fdcId": 175119,
  "usda": "Fish, mackerel, Atlantic, raw",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Seafood",
  "per100g": {
   "kcal": 205.0,
   "protein": 18.6,
   "fat": 13.89,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "smoked_salmon": {
  "fdcId": 173687,
  "usda": "Fish, salmon, chinook, smoked",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Seafood",
  "per100g": {
   "kcal": 117.0,
   "protein": 18.28,
   "fat": 4.32,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "scallops": {
  "fdcId": 174220,
  "usda": "Mollusks, scallop, mixed species, raw",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Seafood",
  "per100g": {
   "kcal": 69.0,
   "protein": 12.06,
   "fat": 0.49,
   "carbs": 3.18,
   "fiber": 0.0
  }
 },
 "halibut": {
  "fdcId": 174200,
  "usda": "Fish, halibut, Atlantic and Pacific, raw",
  "unit": "oz",
  "gramsPerUnit": 28.35,
  "section": "Seafood",
  "per100g": {
   "kcal": 91.0,
   "protein": 18.56,
   "fat": 1.33,
   "carbs": 0.0,
   "fiber": 0.0
  }
 },
 "cauliflower": {
  "fdcId": 169986,
  "usda": "Cauliflower, raw",
  "unit": "cup",
  "gramsPerUnit": 107,
  "section": "Produce",
  "per100g": {
   "kcal": 25.0,
   "protein": 1.92,
   "fat": 0.28,
   "carbs": 4.97,
   "fiber": 2.0
  }
 },
 "asparagus": {
  "fdcId": 168389,
  "usda": "Asparagus, raw",
  "unit": "cup",
  "gramsPerUnit": 134,
  "section": "Produce",
  "per100g": {
   "kcal": 20.0,
   "protein": 2.2,
   "fat": 0.12,
   "carbs": 3.88,
   "fiber": 2.1
  }
 },
 "mushrooms": {
  "fdcId": 169251,
  "usda": "Mushrooms, white, raw",
  "unit": "cup",
  "gramsPerUnit": 70,
  "section": "Produce",
  "per100g": {
   "kcal": 22.0,
   "protein": 3.09,
   "fat": 0.34,
   "carbs": 3.26,
   "fiber": 1.0
  }
 },
 "cabbage": {
  "fdcId": 169975,
  "usda": "Cabbage, raw",
  "unit": "cup",
  "gramsPerUnit": 89,
  "section": "Produce",
  "per100g": {
   "kcal": 25.0,
   "protein": 1.28,
   "fat": 0.1,
   "carbs": 5.8,
   "fiber": 2.5
  }
 },
 "raspberries": {
  "fdcId": 167755,
  "usda": "Raspberries, raw",
  "unit": "cup",
  "gramsPerUnit": 123,
  "section": "Produce",
  "per100g": {
   "kcal": 52.0,
   "protein": 1.2,
   "fat": 0.65,
   "carbs": 11.94,
   "fiber": 6.5
  }
 },
 "strawberries": {
  "fdcId": 167762,
  "usda": "Strawberries, raw",
  "unit": "cup",
  "gramsPerUnit": 152,
  "section": "Produce",
  "per100g": {
   "kcal": 32.0,
   "protein": 0.67,
   "fat": 0.3,
   "carbs": 7.68,
   "fiber": 2.0
  }
 },
 "macadamia": {
  "fdcId": 170178,
  "usda": "Nuts, macadamia nuts, raw",
  "unit": "tbsp",
  "gramsPerUnit": 8.4,
  "section": "Pantry",
  "per100g": {
   "kcal": 718.0,
   "protein": 7.91,
   "fat": 75.77,
   "carbs": 13.82,
   "fiber": 8.6
  }
 }
};
